/*******************************************************
* Fixed.frag Fixed Function Equivalent Fragment Shader *
*   Automatically Generated by 3Dlabs GLSL ShaderGen   *
*             http://developer.3dlabs.com              *
*******************************************************/
uniform mat4 CameraModelViewInverse;

uniform sampler2D Texture0;
uniform sampler2D Texture1;
uniform sampler2D Texture2;
uniform sampler2DShadow ShadowMap;

void main (void) 
{
  vec4 color;
#ifdef ENABLE_TEXTURES
	  color = texture2D(Texture0, gl_TexCoord[0].xy)*gl_Color;
	#if TEXTURE_UNITS > 1
	  color*= texture2D(Texture0, gl_TexCoord[1].xy);
	#endif
	#if TEXTURE_UNITS > 2
	  color*= texture2D(Texture1, gl_TexCoord[2].xy);
	#endif
	 // color.a = gl_Color.a;
#else
  color = gl_Color;
#endif

#ifdef ENABLE_SHADOWS
  float fColor=shadow2DProj(ShadowMap, gl_TexCoord[3]).r;
  color.rgb=mix(color.rgb,color.rgb*gl_LightModel.ambient.rgb,1.0-fColor);
#endif

  gl_FragColor=color;
}
