language: cpp
sudo: true
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libsdl2-dev
    - libsdl2-image-dev
    - libopenal-dev
    - libalut-dev
    - libvorbis-dev
    - gcc-5
    - g++-5

compiler:
    - g++

#Build steps
before_install:
    - wget https://cmake.org/files/v3.9/cmake-3.9.2-Linux-x86_64.tar.gz
    - tar xf cmake-3.9.2-Linux-x86_64.tar.gz
    - rm -v cmake-3.9.2-Linux-x86_64.tar.gz
    - mv -v cmake-3.9.2-Linux-x86_64 cmake392
    - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
    - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
    - cmake392/bin/cmake .

script:
    - make

