/*******************************************************
* Fixed.frag Fixed Function Equivalent Fragment Shader *
*   Automatically Generated by 3Dlabs GLSL ShaderGen   *
*             http://developer.3dlabs.com              *
*******************************************************/
uniform mat4 CameraModelViewInverse;

uniform sampler2D Texture0;
uniform sampler2D Texture1;
uniform sampler2D Texture2;
uniform sampler2DShadow ShadowMap;

#define LIGHTING_SATURATION 1.5

#ifdef ENABLE_LIGHTING
varying vec4 g_amb;
varying vec4 g_diff;
varying vec4 g_spec;
varying vec4 g_sunamb;
varying vec4 g_sundiff;
varying vec4 g_sunspec;
#endif

#ifdef ENABLE_FOG
varying float g_fFogFactor;
#endif 

void main (void) 
{
  vec4 texcolor=gl_Color;
  vec4 finalcolor;
  float fShadowFactor=1.0;
  
  
#ifdef ENABLE_TEXTURES
      texcolor*= texture2D(Texture0, gl_TexCoord[0].xy);
	#if TEXTURE_UNITS > 1
      texcolor*= texture2D(Texture0, gl_TexCoord[1].xy);
	#endif
	#if TEXTURE_UNITS > 2
      texcolor*= texture2D(Texture1, gl_TexCoord[2].xy);
	#endif
#endif
  
  #ifdef ENABLE_LIGHTING
	  vec4 amb=g_amb;
	  vec4 diff=g_diff;
	  vec4 spec=g_spec;
  #endif
  
  #ifdef ENABLE_SHADOWS
	  fShadowFactor=shadow2DProj(ShadowMap, gl_TexCoord[3]).r;
  #endif
  #ifdef ENABLE_LIGHTING
	  amb+=g_sunamb*fShadowFactor;
	  diff+=g_sundiff*fShadowFactor;
	  spec+=g_sunspec*fShadowFactor;
	  finalcolor=(clamp(gl_LightModel.ambient+amb+diff,0.0,LIGHTING_SATURATION)*texcolor)+(spec*gl_FrontMaterial.specular*texcolor);
	  finalcolor.a=texcolor.a;
  #else
	finalcolor=texcolor*fShadowFactor;
  #endif
	
  
  #ifdef ENABLE_FOG
	finalcolor= vec4(clamp(finalcolor.rgb, 0.0, 1.0),finalcolor.a);
	finalcolor.rgb=mix(gl_Fog.color.rgb,finalcolor.rgb,g_fFogFactor);
  #endif

	gl_FragColor=finalcolor;
}